model:
  path: models/yolo11x-pose.xml  # RCNN IR (switch back to YOLO if needed)
  device: CPU
  img_size: 640
  # backend: auto | yolo | rcnn
  backend: auto
input:
  source: 0   # 0 for default webcam
  max_frame: 0
  capture:
    width: 1280   # 0 or omit to keep camera default
    height: 720   # 0 or omit to keep camera default
    fps: 30       # 0 or omit to keep camera default
performance:
  skip: 0
postprocess:
  det_confidence: 0.5
  kpt_confidence: 0.2
  max_detections: 10
  nms_iou: 0.45
draw:
  skeleton: true
  keypoint_radius: 3
  thickness: 2
display:
  width: 1200     # GUI display area width
  height: 900    # GUI display area height
